name = "all-track-remix"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

services = [
  { binding = "api", service = "all-track-api" }
]

[site]
bucket = "./public"

[miniflare.mounts]
all-track-api = "../api"


