name = "all-track-remix"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-01-30"
compatibility_flags = ["streams_enable_constructors"]

routes = [
	{ pattern = "all-track.krolebord.com", custom_domain = true }
]

services = [
  { binding = "api", service = "all-track-api" }
]

[site]
bucket = "./public"

[miniflare]
env_path = "../../.env"

[miniflare.mounts]
all-track-api = "../api"


