name = "all-track-api"
type = "javascript"
workers_dev = true
main = "./build/index.mjs"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

route = "all-track.krolebord.com/api/*"

[env.dev]
route = "miniflare.test/api/*"

[miniflare]
route = "http://127.0.0.1/api*"
env_path = "../../.env"

[build.upload]
format = "modules"
