name = "all-track-api"
type = "javascript"
workers_dev = true
main = "./build/index.mjs"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

[build]
command = "npm run build"
[build.upload]
format = "modules"
